# -*- coding: utf-8 -*-
"""Genera los notebooks de exploracion de datos reales (notebooks/01, 02).

Se construyen desde Python para garantizar JSON valido y evitar el escapado
manual de cadenas en un .ipynb. Ejecutar:  python scripts/build_notebooks.py
"""
from __future__ import annotations

import json
from itertools import count
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "notebooks"
OUT.mkdir(parents=True, exist_ok=True)

_CELL_IDS = count(1)


def _cell_id() -> str:
    """nbformat >= 4.5 exige 'id' en cada celda."""
    return f"cell-{next(_CELL_IDS):03d}"


def md(*lines: str) -> dict:
    return {
        "cell_type": "markdown",
        "id": _cell_id(),
        "metadata": {},
        "source": [l + "\n" for l in lines][:-1] + [lines[-1]],
    }


def code(*lines: str) -> dict:
    src = [l + "\n" for l in lines][:-1] + [lines[-1]]
    return {
        "cell_type": "code",
        "id": _cell_id(),
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": src,
    }


def notebook(cells: list) -> dict:
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def validate(cells: list, name: str) -> None:
    """Compila cada celda de codigo: un error de sintaxis aqui solo apareceria
    al abrir el notebook, que es exactamente cuando mas molesta."""
    for i, c in enumerate(cells):
        if c["cell_type"] != "code":
            continue
        src = "".join(c["source"]) if isinstance(c["source"], list) else c["source"]
        try:
            compile(src, f"{name}::cell{i}", "exec")
        except SyntaxError as exc:
            raise SystemExit(
                f"{name}: celda de codigo {i} con error de sintaxis: {exc.msg} (linea {exc.lineno})\n"
                f"  {exc.text!r}"
            ) from exc


PRELUDE = [
    "import sys",
    "from pathlib import Path",
    "",
    "import numpy as np",
    "import pandas as pd",
    "",
    "ROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()",
    "sys.path.insert(0, str(ROOT / 'src'))",
    "sys.path.insert(0, str(ROOT))",
    "",
    "from src.utils.configloader import expand_path, load_catalogs, load_settings, load_sources",
    "",
    "pd.set_option('display.max_columns', 40)",
    "pd.set_option('display.width', 160)",
    "",
    "SETTINGS = load_settings()",
]

# ---------------------------------------------------------------- ONSV ----

onsv = [
    md(
        "# 01 · Perfilado del crudo ONSV",
        "",
        "Fase CRISP-DM **Data Understanding**. Carga el XLSX real *tal como llega* y",
        "documenta los problemas que la capa de limpieza debe resolver.",
        "",
        "El objetivo NO es limpiar: es ver el dato sucio antes de decidir qué se limpia.",
        "",
        "Preguntas que responde:",
        "",
        "1. Donde esta la cabecera real del fichero?",
        "2. Que columnas mezclan tipos y por qué no son escribibles en Parquet?",
        "3. Que tanta informacion se pierde en cada limpieza?",
        "4. Que reglas de dominio se pueden escribir a partir de la observacion?",
    ),
    code(*PRELUDE, 'spec = load_sources()["onsv"].copy()', 'spec["path"] = expand_path(spec["path"])',
         'print("Fuente:", spec["path"])', 'print("Existe:", Path(spec["path"]).exists())'),
    md("## 1.1 · Donde esta la cabecera",
        "",
        "El XLSX de ONSV tiene un preambulo institucional antes de los encabezados.",
        "Leerlo con `pd.read_excel(path)` sin indicar `header` toma la primera fila",
        "del preambulo como cabecera y todos los nombres quedan corruptos."),
    code('naive = pd.read_excel(spec["path"], header=0, nrows=3)',
         'correct = pd.read_excel(spec["path"], header=spec["header_row"], nrows=3)',
         "",
         'print("Con header=0 (ingenuo), primeras columnas:")',
         "print(list(naive.columns)[:6], \"...\")",
         "",
         'print(f"Con header_row={spec[\'header_row\']} (configurado):")',
         "print(list(correct.columns))"),
    md("## 1.2 · Nombres problematicos",
        "",
        "Acentos, signos de interrogacion de apertura y espacios dobles. Cada uno",
        "requiere una decision explicita de renombrado, no un `.strip()` generico."),
    code("cols = list(correct.columns)",
         "problemas = {",
         "    'espacios dobles': [c for c in cols if '  ' in c],",
         "    'signo apertura (¿)': [c for c in cols if '¿' in c],",
         "    'acentos': [c for c in cols if any(ch in c for ch in 'ÁÉÍÓÚÑáéíóúñ')],",
         "}",
         "for k, v in problemas.items():",
         "    print(f'{k}: {len(v)}')",
         "    for c in v:",
         "        print('    ', repr(c))"),
    md("## 1.3 · Tipos mezclados (el problema que rompia Bronze)",
        "",
        "Parquet exige **un tipo por columna**. Las columnas `object` que mezclan",
        "tipos no son escribibles: PyArrow lanza",
        "`Expected bytes, got a 'datetime.datetime' object`."),
    code("import datetime as dt", "",
         'raw = pd.read_excel(spec["path"], header=spec["header_row"])',
         'print(f"Crudo: {raw.shape[0]:,} filas x {raw.shape[1]} columnas\\n")',
         "",
         "for col in raw.columns:",
         "    s = raw[col]",
         "    if s.dtype != object:",
         "        continue",
         "    tipos = set(type(v).__name__ for v in s.dropna())",
         "    if len(tipos) > 1:",
         "        print(f'{col!r} -> {sorted(tipos)}')",
         "        for v in s.dropna().unique()[:3]:",
         "            print('     ', repr(v))"),
    md("### Comprobacion directa: se puede escribir en Parquet?"),
    code("import tempfile", "",
         'tmp = Path(tempfile.gettempdir()) / "nb_bronze_test.parquet"',
         "try:",
         '    raw.to_parquet(tmp, engine="pyarrow", index=False)',
         '    print("OK: el crudo se escribe directo en Parquet")',
         "except Exception as exc:",
         '    print("FALLA (como en produccion):", type(exc).__name__)',
         "    print('  ', str(exc)[:140])"),
    md("## 1.4 · La solucion aplicada: `_parquet_safe()`",
        "",
        "Normaliza **por contenido**, no por nombre de columna, en tres pasos:",
        "numerico -> fecha -> literal, aceptando la conversion solo si no destruye valores."),
    code("from src.extract.register_raw import _parquet_safe", "",
         "fixed = _parquet_safe(raw.copy())",
         'print(f"Tras _parquet_safe: {fixed.shape[0]:,} filas x {fixed.shape[1]} columnas")',
         "fixed.to_parquet(tmp, engine='pyarrow', index=False)",
         'print("Se escribe en Parquet: si\\n")',
         "",
         "back = pd.read_parquet(tmp)",
         "assert len(back) == len(raw), 'no se pierden filas'",
         'print("Filas preservadas:", f"{len(back):,}")',
         "",
         "cambiadas = [c for c in raw.columns if str(raw[c].dtype) != str(back[c].dtype)]",
         "print('Columnas cuyo tipo cambio en Bronze:', cambiadas)"),
    md("## 1.5 · Completitud y nulos por columna",
        "",
        "Base para decidir imputaciones. Solo se imputa lo que tiene sentido imputar."),
    code("nulos = pd.DataFrame({",
         "    'nulos': raw.isna().sum(),",
         "    'pct_nulos': (raw.isna().mean() * 100).round(2),",
         "    'n_unicos': raw.nunique(dropna=True),",
         "    'dtype': raw.dtypes.astype(str),",
         "}).sort_values('pct_nulos', ascending=False)",
         "nulos[nulos['pct_nulos'] > 0]"),
    md("## 1.6 · Categoricas: que valores existen",
        "",
        "Base empirica de `config/quality/catalogs/onsv.yaml`."),
    code('for col in ["CLASE SINIESTRO", "CONDICIÓN CLIMÁTICA", "ZONA", "RED VIAL"]:',
         "    if col not in raw.columns:",
         "        continue",
         '    print(f"\\n=== {col} ({raw[col].nunique()} unicos) ===")',
         "    print(raw[col].value_counts(dropna=False).head(12).to_string())"),
    md("## 1.7 · El problema de los acentos",
        "",
        "`CAÍDA DE PASAJERO` -> `CAIDA DE PASAJERO` tras `fold_accents`.",
        "Si el catalogo mantiene el acento, la comparacion falla siempre."),
    code('cats = load_catalogs("onsv")',
         'print("Catalogo (forma plegada, la que produce Silver):")',
         "for v in cats['clase']:",
         "    print('   ', v)",
         "",
         'print("\\nValores en el crudo:")',
         "cat_upper = {c.upper() for c in cats['clase']}",
         'for v in sorted(raw["CLASE SINIESTRO"].dropna().unique()):',
         "    marca = 'OK' if v.upper() in cat_upper else 'DIFIERE'",
         "    print(f'    {v!r}  {marca}')"),
    md("## 1.8 · Coordenadas: el Peru es negativo",
        "",
        "Este detalle hizo fallar la dimension de validez en una version anterior:",
        "un umbral `>= 0` aplicado a coordenadas de un pais del hemisferio sur."),
    code('lat = pd.to_numeric(raw["COORDENADAS LATITUD"].astype(str)',
         '                       .str.replace("°", "", regex=False), errors="coerce")',
         'lon = pd.to_numeric(raw["COORDENADAS  LONGITUD"].astype(str)',
         '                       .str.replace("°", "", regex=False), errors="coerce")',
         "",
         'print("Latitud :", round(lat.min(), 4), "a", round(lat.max(), 4))',
         'print("Longitud:", round(lon.min(), 4), "a", round(lon.max(), 4))',
         'print(f"\\nPct latitudes  negativas: {(lat < 0).mean() * 100:.1f}%")',
         'print(f"Pct longitudes negativas: {(lon < 0).mean() * 100:.1f}%")',
         'print("\\n=> Un chequeo de validez >= 0 puntuaria 0% a ambas columnas.\\n")',
         "dentro = lat.between(-18.5, 0.2) & lon.between(-81.5, -68.5)",
         'print(f"Dentro del territorio peruano: {dentro.mean() * 100:.1f}%")'),
    md("## 1.9 · Fechas: DD/MM vs MM/DD",
        "",
        "Pandas interpreta `01/05/2021` como 1 de mayo cuando el dato es 5 de enero."),
    code('fechas_texto = raw["FECHA SINIESTRO"].dropna().astype(str)',
         "print('Muestra:', fechas_texto.head(5).tolist(), '\\n')",
         'ingenua = pd.to_datetime(fechas_texto, errors="coerce")',
         'correcta = pd.to_datetime(fechas_texto, format="%d/%m/%Y", errors="coerce")',
         "",
         'print(f"NaT con parsing por defecto: {ingenua.isna().sum()}")',
         'print(f"NaT con format=%d/%m/%Y : {correcta.isna().sum()}")',
         'print(f"\\nRango correcto: {correcta.min().date()} a {correcta.max().date()}")',
         "print('Rango ingenuo :', ingenua.min(), 'a', ingenua.max())",
         'print("\\n=> Configurar date_columns en settings.yaml NO es opcional.")'),
    md("## 1.10 · Duplicados en la clave primaria"),
    code('clave = "CÓDIGO SINIESTRO"',
         'print("Filas        :", f"{len(raw):,}")',
         'print("Codigos unicos:", f"{raw[clave].nunique():,}")',
         'print("Duplicados   :", int(raw[clave].duplicated().sum()))',
         'print("Nulos en la PK:", int(raw[clave].isna().sum()))',
         "",
         "dup = raw[raw[clave].duplicated(keep=False)].sort_values(clave)",
         "if len(dup):",
         "    print('\\nFilas implicadas:', len(dup))",
         "    print(dup[[clave, 'FECHA SINIESTRO', 'CLASE SINIESTRO']].head(10).to_string(index=False))",
         "else:",
         "    print('\\nNo hay duplicados: la PK codigo es unica de origen.')"),
    md("## 1.11 · Perfil del target",
        "",
        "`fallecidos` es el target de `model_ready`. Su distribucion determina que modelo",
        "tendra sentido (conteo desbalanceado -> Poisson/Tweedie, no regresion lineal)."),
    code('f = pd.to_numeric(raw["CANTIDAD DE FALLECIDOS"], errors="coerce").fillna(0)',
         "print(f.describe().to_string())",
         'print("\\nDistribucion de fallecidos por siniestro:")',
         "print(f.astype(int).value_counts().sort_index().head(10).to_string())"),
    md("## 1.12 · Variables categoricas frente al target"),
    code('f = pd.to_numeric(raw["CANTIDAD DE FALLECIDOS"], errors="coerce").fillna(0)',
         'for col in ["CLASE SINIESTRO", "ZONA", "CONDICIÓN CLIMÁTICA"]:',
         "    if col not in raw.columns:",
         "        continue",
         '    g = raw.assign(_f=f).groupby(col, dropna=False)["_f"].agg(["count", "mean"])',
         "    g['pct'] = (g['count'] / len(raw) * 100).round(2)",
         "    g['media_fallecidos'] = g['mean'].round(3)",
         '    print(f"\\n--- {col} ---")',
         "    print(g[['pct', 'media_fallecidos']].head(10).to_string())",
         'print(f"\\nMedia global: {f.mean():.3f} fallecidos por siniestro")'),
    md("## 1.13 · Conclusiones",
        "",
        "| Hallazgo | Decision de diseno |",
        "|---|---|",
        "| Preambulo de 4 filas | `header_row: 4` en la config de la fuente |",
        "| Nombres con acentos, `¿?` y espacios dobles | mapa `rename` canonico |",
        "| Fechas DD/MM ambiguas | `date_columns` con formatos explicitos |",
        "| Coordenadas con simbolo grado | `numeric_strip_chars` |",
        "| Columnas `object` con tipos mezclados | `_parquet_safe()` en Bronze |",
        "| Acentos en categorias | catalogos en forma plegada + comparacion `_norm()` |",
        "| Coordenadas negativas (Peru) | `validity` usa el rango del contrato |",
        "",
        "Todos estos puntos estan cubiertos por `tests/unit/test_regressions.py`."),
]

# -------------------------------------------------------- CINEMOMETROS ----

cine = [
    md(
        "# 02 · Perfilado del crudo Cinemometros (SUTRAN)",
        "",
        "Segunda fuente, deliberadamente distinta: 160.018 filas en CSV frente a un XLSX",
        "de 9.106 filas. Aqui los problemas son de **normalizacion**, no de formato:",
        "",
        "- `REGION` con `LIMA` y `Lima` a la vez (doble caja)",
        "- `CARRETERA` con `Panamericana Sur` frente a `PANAMERICANA SUR`",
        "- `lat`/`lon` que duplican exactamente `LATITUD`/`LONGITUD`",
        "- Fechas en formato numerico compactado (`20191031`)",
        "",
        "Al ser un dataset mucho mayor, se mide tambien el coste de la normalizacion.",
    ),
    code(*PRELUDE, 'spec = load_sources()["cinemometros"].copy()', 'spec["path"] = expand_path(spec["path"])',
         'print("Fuente:", spec["path"])', 'print("Existe:", Path(spec["path"]).exists())'),
    code("import csv", "",
         "with open(spec['path'], encoding='utf-8-sig') as fh:",
         "    reader = csv.reader(fh)",
         "    header = next(reader)",
         "    first = next(reader)",
         'print("Columnas:", len(header))',
         "for h in header:",
         "    print('   ', repr(h))",
         "print('\\nPrimera fila:'); print(first)"),
    md("## 2.1 · La doble caja en REGION",
        "",
        "El problema de normalizacion clasico: la misma entidad escrita de dos formas."),
    code('cine = pd.read_csv(spec["path"], encoding="utf-8-sig", low_memory=False)',
         'print(f"Crudo: {cine.shape[0]:,} filas x {cine.shape[1]} columnas\\n")',
         'print("Valores de REGION tal cual llegan:")',
         "print(cine['REGION'].value_counts(dropna=False).to_string())"),
    md("### Cuantas filas se ven afectadas por la doble caja"),
    code('es_minuscula = cine["REGION"].astype(str) != cine["REGION"].astype(str).str.upper()',
         'print("Filas con REGION no normalizada:", f"{int(es_minuscula.sum()):,}",',
         '      f"({es_minuscula.mean()*100:.2f}%)")',
         "print('Valores afectados:', sorted(cine.loc[es_minuscula, 'REGION'].unique()))",
         'print("\\n=> Sin case_normalize, el mismo departamento seria dos categorias distintas.")'),
    md("## 2.2 · CARRETERA tambien tiene doble caja"),
    code('print("Valores de CARRETERA:")',
         "print(cine['CARRETERA'].value_counts(dropna=False).head(20).to_string())"),
    md("## 2.3 · Fechas en formato numerico compactado",
        "",
        "`20191031` es un entero, no una fecha. Sin `date_columns` con `%Y%m%d` el pipeline",
        "no puede parsearlas y la regla critica `fecha_parsable` falla."),
    code('print("Dtype crudo de FECHA_PAPELETA:", cine["FECHA_PAPELETA"].dtype)',
         "print('Muestra:', cine['FECHA_PAPELETA'].head(5).tolist(), '\\n')",
         'parseada = pd.to_datetime(cine["FECHA_PAPELETA"], format="%Y%m%d", errors="coerce")',
         'print("NaT con format=%Y%m%d:", int(parseada.isna().sum()))',
         'print("Rango:", parseada.min(), "a", parseada.max())',
         'print("\\n=> Configurar el formato compacto es obligatorio, no opcional.")'),
    md("## 2.4 · Columnas redundantes: lat/lon vs LATITUD/LONGITUD",
        "",
        "La configuracion descarta `lat`/`lon`. Este notebook verifica que la duplicacion es",
        "exacta antes de tomar esa decision."),
    code('if "lat" in cine.columns and "lon" in cine.columns:',
         "    mismo_lat = (cine['lat'].astype(float) == cine['LATITUD'].astype(float)).mean()",
         "    mismo_lon = (cine['lon'].astype(float) == cine['LONGITUD'].astype(float)).mean()",
         '    print(f"Pct de filas donde lat == LATITUD: {mismo_lat*100:.2f}%")',
         '    print(f"Pct de filas donde lon == LONGITUD: {mismo_lon*100:.2f}%")',
         '    print("\\n=> Duplicacion exacta: se descartan en clean (drop_columns).")',
         "else:",
         '    print("El fichero ya no trae lat/lon.")'),
    md("## 2.5 · Nulos y completitud"),
    code("nulos = pd.DataFrame({",
         "    'nulos': cine.isna().sum(),",
         "    'pct_nulos': (cine.isna().mean() * 100).round(2),",
         "    'n_unicos': cine.nunique(dropna=True),",
         "}).sort_values('pct_nulos', ascending=False)",
         "nulos[nulos['pct_nulos'] > 0]"),
    md("## 2.6 · Velocidades: el dominio de negocio",
        "",
        "El exceso de velocidad es la magnitud accionable. Se derivan `exceso_kmh` y",
        "`excede_limite` en `src/transform/features.py`."),
    code('v = pd.to_numeric(cine["VELOCIDAD_DETECTADA"], errors="coerce")',
         'lim = pd.to_numeric(cine["LIMITE_VELOCIDAD"], errors="coerce")',
         "v, lim = v.dropna(), lim.loc[v.dropna().index]",
         'print("Velocidad detectada:")',
         "print(v.describe().round(2).to_string(), '\\n')",
         'print("Limite de velocidad:")',
         "print(lim.value_counts(dropna=False).head(10).to_string(), '\\n')",
         "exceso = (v - lim).clip(lower=0)",
         'print("Exceso sobre el limite (km/h):")',
         "print(exceso.describe().round(2).to_string())",
         'print(f"\\nPct que excede el limite: {(exceso > 0).mean()*100:.2f}%")',
         'print("Pct que excede mas de 20 km/h: %.2f%%" % ((exceso > 20).mean()*100))'),
    md("### Outliers: se reportan, no se eliminan",
        "",
        "`outlier_policy: report`. Un exceso alto es informacion real, no basura."),
    code("q1, q3 = exceso.quantile([0.25, 0.75])",
         "iqr = q3 - q1",
         "lim_sup = q3 + 1.5 * iqr",
         'print(f"IQR: Q1={q1:.1f}, Q3={q3:.1f}, umbral superior={lim_sup:.1f} km/h")',
         'print(f"Outliers por IQR: {int((exceso > lim_sup).sum()):,} '
         '({(exceso > lim_sup).mean()*100:.2f}%)")',
         'print("\\n=> Se reportan en el perfil. Borrarlos seria una decision analitica, no de limpieza.")'),
    md("## 2.7 · Duplicados en la clave primaria"),
    code('clave = "NRO_DETECCION"',
         'print("Filas         :", f"{len(cine):,}")',
         'print("Detecciones   :", f"{cine[clave].nunique():,}")',
         'print("Duplicados    :", int(cine[clave].duplicated().sum()))',
         'print("Nulos en la PK:", int(cine[clave].isna().sum()))',
         "if cine[clave].duplicated().any():",
         "    d = cine[cine[clave].duplicated(keep=False)]",
         '    print("\\nMuestra de duplicados:")',
         "    print(d.head(10).to_string())",
         "else:",
         '    print("\\nPK unica: no se requiere dedupe en este dataset.")'),
    md("## 2.8 · Distribucion geografica"),
    code("print('Top 10 regiones por numero de detecciones:')",
         "print(cine['REGION'].value_counts().head(10).to_string())"),
    md("## 2.9 · Conclusion: contraste con ONSV",
        "",
        "| Aspecto | ONSV (9.106 filas) | Cinemometros (160.018 filas) |",
        "|---|---|---|",
        "| Formato | XLSX con preambulo | CSV plano |",
        "| Problema dominante | estructura (nombres, tipos) | normalizacion (caja, acentos) |",
        "| Fechas | `DD/MM/YYYY` ambiguo | `%Y%m%d` numerico |",
        "| Columnas redundantes | ninguna | `lat`/`lon` duplican |",
        "| PK | `codigo`, unica | `nro_deteccion`, unica |",
        "| Nulos relevantes | `vehiculos_danados` 30.9% | ninguno critico |",
        "",
        "Un pipeline que solo funciona con uno de los dos formatos no es un pipeline."),
]

validate(onsv, "01_exploracion_onsv")
validate(cine, "02_exploracion_cinemometros")

silver = [
    md(
        "# 03 · Silver, DQS y quality gate",
        "",
        "Fase CRISP-DM **Data Preparation / Evaluation**. Este notebook carga la Silver",
        "ya generada por el pipeline y muestra:",
        "",
        "1. Que hizo la limpieza (TransformationLog, no conjeturas)",
        "2. Como se descompone el DQS en sus seis dimensiones",
        "3. Que pasaria si una regla critica fallara",
        "4. Las agregaciones Gold generadas con SQL sobre DuckDB",
        "",
        "Requisito previo: `python scripts/run_pipeline.py`",
    ),
    code(*PRELUDE, "from src.cleaning.transform_log import TransformationLog", "",
         "from pathlib import Path", "",
         'SILVER = ROOT / "data" / "silver"',
         'print("Silver disponible:", SILVER.exists())',
         'print([p.name for p in sorted(SILVER.glob("*.parquet"))] if SILVER.exists() else "ejecuta el pipeline")'),
    md("## 3.1 · Que se limpio realmente: el TransformationLog",
        "",
        "No se supone nada: cada operacion queda registrada con el numero de registros",
        "afectados y ejemplos antes/despues."),
    code("import json", "",
         "runs = sorted((ROOT / 'artifacts' / 'runs').glob('run-*'), reverse=True)",
         'print("Ultimo run:", runs[0].name if runs else "ninguno")',
         "tlog_path = runs[0] / 'transform_log_onsv.json' if runs else None",
         "if tlog_path and tlog_path.exists():",
         "    tlog = json.loads(tlog_path.read_text(encoding='utf-8'))",
         "    ops = tlog['operations']",
         "    print(f'\\n{len(ops)} operaciones registradas\\n')",
         "    resumen = pd.DataFrame([{",
         "        'operacion': o['operation'],",
         "        'columna': o.get('column'),",
         "        'afectados': o.get('n_affected'),",
         "        'estrategia': o.get('strategy'),",
         "    } for o in ops])",
         "    print(resumen.to_string(index=False))",
         "else:",
         "    print('No hay transform log: ejecuta el pipeline.')"),
    md("## 3.2 · Silver: estructura y contrato"),
    code("from src.utils.configloader import load_contract", "",
         "from src.validation.contract import validate_contract", "",
         'sl = pd.read_parquet(SILVER / "onsv_silver_1.0.parquet")',
         'print(f"Silver ONSV: {sl.shape[0]:,} filas x {sl.shape[1]} columnas\\n")',
         "print('Columnas canónicas:')",
         "for i, c in enumerate(sl.columns, 1):",
         "    print(f'  {i:2d}. {c:<28} {sl[c].dtype}')"),
    code('contract = load_contract("onsv", SETTINGS)',
         "res = validate_contract(sl, contract)",
         'print(f"\\nContrato valido: {res[\'valid\']}  (errores: {res[\'n_errors\']})")',
         "if res['errors']:",
         "    for col, rule, msg in res['errors'][:10]:",
         "        print(f'   {col}: {rule} -> {msg}')",
         'print("\\nColumnas extra toleradas (allow_extra):")',
         "print('  ', res['details_by_column'].get('__extra_columns'))"),
    md("## 3.3 · DQS descompuesto",
        "",
        "El DQS es una media ponderada de seis dimensiones. Verlas por separado explica",
        "mucho mas que el numero final."),
    code("from src.quality import dimensions", "",
         "from src.utils.configloader import load_catalogs", "",
         'cd = load_contract("onsv", SETTINGS)',
         'dqs = dimensions.compute_dqs(sl, SETTINGS, cd, load_catalogs("onsv"), dataset="onsv")',
         "pesos = dqs['weights']",
         "print('Dimension      Peso    Valor   Aporte')",
         "print('-' * 46)",
         "for k in pesos:",
         "    print(f'{k:<14} {pesos[k]:.2f}  {dqs[k]:7.2f}  {dqs[k]*pesos[k]:7.2f}')",
         "print('-' * 46)",
         "print(f'{\"DQS\":<14} {\"1.00\":<6} {\"\":>7}  {dqs[\"dqs\"]:7.2f}')",
         "print(f'\\nFilas evaluadas: {dqs[\"n_rows\"]:,}')",
         "print(f'Columna de frescura: {dqs[\"freshness_column\"]} (ventana {dqs[\"freshness_window_days\"]} d)')"),
    md("### Por que la frescura es baja y eso es correcto",
        "",
        "Los siniestros son de 2021-2025. Un registro de 2021 no es fresco en 2026: es un",
        "dato historico. Por eso la frescura pesa 0.08 y el sistema lo dice en vez de"),
    code("print(f'Frescura: {dqs[\"freshness\"]:.2f}')",
         "print('Es una consecuencia de que la fuente es historica, no un defecto del proceso.')",
         "print('Si la fuente se actualiza, el DQS sube solo, sin tocar configuracion.')"),
    md("## 3.4 · Validacion de la correccion del DQS",
        "",
        "Si `validity` aplicase `>= 0` a toda columna numerica, las coordenadas del Peru",
        "(negativas) puntuarian 0%. Comprobamos que ya no es asi."),
    code('rango_lat = (sl["latitud"].between(-18.5, 0.2)).mean() * 100',
         'rango_lon = (sl["longitud"].between(-81.5, -68.5)).mean() * 100',
         'print(f"Latitud dentro de rango:  {rango_lat:.2f}%")',
         'print(f"Longitud dentro de rango: {rango_lon:.2f}%")',
         'print(f"\\n=> Un umbral >= 0 habria dado 0.00% en ambas. Correccion aplicada.")'),
    md("## 3.5 · Features derivadas"),
    code("features = [c for c in sl.columns if c not in load_contract('onsv', SETTINGS)['contract']['columns']]",
         "print('Features derivadas por src/transform/features.py:')",
         "for f in features:",
         "    print(f'   {f:<22} {sl[f].dtype}')",
         "",
         "if 'tramo_dia' in sl.columns:",
         '    print("\\nSiniestros por tramo del dia:")',
         "    print(sl['tramo_dia'].value_counts().to_string())"),
    md("## 3.6 · Simular el fallo de una regla critica",
        "",
        "El sistema esta disenado para detenerse. Inyectamos una violacion y comprobamos",
        "que el gate la detecta y que el registro llega a cuarentena."),
    code("from src.quality.domain_rules import detect_violations", "",
         "from src.quality.gates import evaluate_gate", "",
         "from src.utils.configloader import load_quality_rules", "",
         "contaminado = sl.copy()",
         "contaminado.loc[contaminado.index[:5], 'latitud'] = 99.0",
         "print('Inyectadas 5 coordenadas fuera del rango peruano (99.0)\\n')",
         "viol = detect_violations(",
         "    contaminado,",
         "    load_quality_rules()['domain_rules']['onsv']['rules'],",
         "    load_catalogs('onsv'),",
         ")",
         "crit = [v for v in viol if v['severity'] == 'critical']",
         "print('Reglas criticas disparadas:')",
         "for v in crit:",
         "    print(f\"   {v['rule']}: {v['count']} registros\")",
         "",
         "gate = evaluate_gate(",
         "    dimensions.compute_dqs(contaminado, SETTINGS, cd, load_catalogs('onsv'), dataset='onsv'),",
         "    viol,",
         "    load_quality_rules(),",
         "    'onsv',",
         "    'demo-run',",
         ")",
         'print(f"\\nGate resultante: {gate[\'status\']}  (criticos: {gate[\'n_critical_errors\']})")',
         'print("\\n=> El gate bloquea la publicacion en Gold model_ready.")'),
    md("## 3.7 · Agregaciones Gold generadas con SQL",
        "",
        "Declaradas en `config/quality/catalogs/*.yaml` y ejecutadas sobre DuckDB."),
    code("from src.utils.configloader import load_aggregations", "",
         "print('Agregaciones declaradas para onsv:')",
         "for spec in load_aggregations('onsv'):",
         "    val = f\", value={spec['value']}\" if 'value' in spec else ''",
         "    print(f\"   {spec['name']:<32} kind={spec['kind']:<9} by={spec['by']}{val}\")"),
    code("agg = sorted((ROOT / 'reports' / 'quality' / 'aggregations').glob('onsv_*.json'))",
         "if agg:",
         "    latest = json.loads(agg[-1].read_text(encoding='utf-8'))",
         "    for name, rows in latest['aggregations'].items():",
         "        print(f'\\n--- {name} ({len(rows)} filas) ---')",
         "        print(pd.DataFrame(rows).head(8).to_string(index=False))",
         "else:",
         "    print('No hay agregaciones: ejecuta el pipeline.')"),
    md("## 3.8 · Consulta SQL directa sobre la capa Silver",
        "",
        "DuckDB lee los Parquet: no hay base de datos que mantener."),
    code("import duckdb", "",
         'silver_glob = str((ROOT / "artifacts" / "lineage" / "sipat_lineage.duckdb").resolve())',
         "con = duckdb.connect(silver_glob, read_only=True)",
         "try:",
         "    print(con.execute(",
         '        "SELECT dataset, layer, rows, cols FROM dataset_lines ORDER BY created_at DESC LIMIT 6"',
         "    ).df().to_string(index=False))",
         "finally:",
         "    con.close()"),
    code("con = duckdb.connect()",
         "try:",
         "    sl_path = str((ROOT / 'data' / 'silver' / 'onsv_silver_1.0.parquet').resolve())",
         "    out = con.execute(",
         '        "SELECT departamento, COUNT(*) AS n, SUM(fallecidos) AS muertos "',
         "        + f\"FROM read_parquet('{sl_path}') \"",
         '        + "GROUP BY 1 ORDER BY muertos DESC, n DESC LIMIT 10"',
         "    ).df()",
         "    print(out.to_string(index=False))",
         "finally:",
         "    con.close()"),
    md("## 3.9 · Conclusiones",
        "",
        "1. La limpieza deja traza auditable en el TransformationLog.",
        "2. El DQS se descompone y cada dimensión es explicable.",
        "3. El gate detiene la publicación ante una regla critica (ver 3.6).",
        "4. Las agregaciones son SQL en YAML, no codigo.",
        "5. La capa Silver es consultable con SQL sin servidor adicional."),
]

validate(silver, "03_silver_dqs_gate")

# ------------------------------------------------------- CONFIABILIDAD ----
#
# El helper `_show` incrusta un PNG en base64. Es OBLIGATORIO aquí en lugar de
# `plt.show()`: `src/quality/figures.py` hace `matplotlib.use('Agg')` al
# importarse, y con Agg el render inline se convierte en un no-op (las celdas
# "ejecutan sin error" pero no muestran nada). Las figuras se generan en disco
# con el mismo código que usa `scripts/graficos_etl.py`, y se incrustan desde
# ahí: una sola implementación, no dos.

_AUDITORIA_PRELUDE = [
    "import base64 as _b64",
    "",
    "from IPython.display import Image as _Image, display",
    "",
    "from src.quality import figures as F",
    "from src.quality import auditoria as R",
    "",
    "",
    "def _show(png_path):",
    "    \"\"\"Incrusta un PNG en el notebook (Agg no permite plt.show()).\"\"\"",
    "    p = Path(png_path)",
    "    if not p.exists():",
    "        print('Falta', p, '- ejecuta: python scripts/graficos_etl.py')",
    "        return",
    "    display(_Image(data=_b64.b64decode(_b64.b64encode(p.read_bytes()))))",
]

rel = [
    md(
        "# 04 · Auditoría de la medición",
        "",
        "Fase CRISP-DM **Evaluation**. Este notebook audita **las métricas que",
        "calcula el ETL**, no el dato ni la predicción:",
        "",
        "| Apartado | Qué audita | Dónde vive |",
        "|---|---|---|",
        "| **Auditoría de la medición** (este) | Si el 92.07 y sus ejes son defendibles | ETL |",
        "| **Fiabilidad de las fuentes** | Si los datos que entrega ONSV/SUTRAN/OSITRAN son de fiar | SIPAT raíz |",
        "| **Validez predictiva** | Si la predicción aguanta fuera de la muestra | SIPAT raíz |",
        "",
        "El DQS mide **propiedades del dato** (nulos, rangos, unicidad). La auditoría",
        "de la medición responde otra cosa: ¿ese 92.07 es un hecho o el resultado de",
        "decisiones mías?, ¿cuánta incertidumbre tiene?, ¿qué parte de la validación",
        "es tautológica?",
        "",
        "> **No se calcula un \"índice de confiabilidad\".** Un número único repetiría",
        "> el error que hace malinterpretable el DQS. En su lugar se produce una",
        "> **tabla de afirmaciones verificables**, cada una con su veredicto, su",
        "> evidencia medida y su límite conocido.",
        "",
        "Todo lo que hay aquí se **calcula** con `src/quality/auditoria.py`: no hay",
        "ni un solo número escrito a mano.",
        "",
        "Requisito previo: `python scripts/run_pipeline.py`",
    ),
    md("## 4.1 · Qué ejes se evalúan",
        "",
        "| Eje | La pregunta incómoda que responde |",
        "|---|---|",
        "| Reproducibilidad | ¿Da el pipeline el mismo resultado si se ejecuta otra vez? |",
        "| Trazabilidad | ¿Se puede trazar el origen de cada número publicado? |",
        "| Robustez del DQS | ¿El 92.07 depende de los pesos que elegí yo? |",
        "| Incertidumbre | ¿Cuánta incertidumbre tiene el DQS que se publica? |",
        "| **Circularidad** | ¿La validación contra catálogos es real o tautológica? |",
        "| Cobertura del universo | ¿El dataset representa todos los siniestros? |",
        "| Integridad referencial | ¿La dimensión `integrity` aporta información? |",
        "| Consistencia cruzada | ¿ONSV y cinemómetros coinciden en su geografía? |",
        "| Imputación | ¿Qué métricas son mediciones y cuáles estimaciones? |",
        "| Deriva temporal | ¿La calidad se mantiene en el tiempo? |",
        "",
        "Los veredictos posibles son `alta`, `media`, `baja` y `no_verificable`.",
        "`no_verificable` no es un fallo: es una frontera honesta, el punto donde",
        "los datos disponibles dejan de poder responder.",
    ),
    code(*PRELUDE, *_AUDITORIA_PRELUDE,
         "",
         "def _silver(ds):",
         "    v = SETTINGS['datasets'][ds]['version']",
         "    p = ROOT / 'data' / 'silver' / f'{ds}_silver_{v}.parquet'",
         "    return pd.read_parquet(p) if p.exists() else None",
         "",
         "",
         "frames = {ds: _silver(ds) for ds in SETTINGS['datasets']}",
         "frames = {k: v for k, v in frames.items() if v is not None}",
         "print('Silver disponible:', {k: v.shape for k, v in frames.items()})",
         "if not frames:",
         "    print('Sin Silver: ejecuta primero python scripts/run_pipeline.py')"),
    code("assess = {}",
         "for ds, df in frames.items():",
         "    otros = {k: v for k, v in frames.items() if k != ds}",
         "    assess[ds] = R.assess(ds, df, settings=SETTINGS, other_frames=otros)",
         "    print(f\"{ds:14} DQS {assess[ds]['dqs']['dqs']:6.2f}   \"",
         "          f\"{assess[ds]['resumen_veredictos']}\")"),
    md("## 4.2 · La tabla de afirmaciones",
        "",
        "Cada fila es una afirmación verificable: la pregunta, el veredicto, la evidencia",
        "medida y el límite que la acota. El veredicto no es un número del eje: es un",
        "dictamen sobre si ese eje se puede sostener."),
    code("def _tabla_claims(res):",
         "    filas = []",
         "    for c in res['claims']:",
         "        ev = c['evidence']",
         "        # El evidence puede traer dicts/listas anidados; para la tabla se",
         "        # aplana a los escalares, que son los valores citables.",
         "        simple = {k: v for k, v in ev.items() if not isinstance(v, (dict, list))}",
         "        filas.append({",
         "            'id': c['id'],",
         "            'eje': c['axis'],",
         "            'veredicto': c['verdict'],",
         "            'evidencia': ', '.join(f'{k}={v}' for k, v in simple.items()),",
         "        })",
         "    return pd.DataFrame(filas)",
         "",
         "",
         "for ds, res in assess.items():",
         "    print(f\"\\n=== {ds}: {res['resumen_veredictos']} ===\")",
         "    display(_tabla_claims(res))"),
    md("## 4.3 · Robustez del DQS: ¿de quién es el 92.07?",
        "",
        "La pregunta que casi nunca se hace a un indicador ponderado: *el peso 0.22 de",
        "completitud lo elegiste tú, así que el 92.07 también es tuyo*. La respuesta se",
        "recalcula con 300 perturbaciones de los pesos y con cuatro escenarios declarados",
        "en `config/quality/auditoria_rules.yaml`."),
    code("for ds, res in assess.items():",
         "    ws = res['detalle']['weight_sensitivity']",
         "    print(f\"\\n=== {ds} ===\")",
         "    print(f\"  spread p05-p95 = {ws['spread_p05_p95']:.2f} puntos \"",
         "          f\"({ws['n_samples']} perturbaciones)\")",
         "    print(f\"  p05={ws['distribucion']['p05']:.2f}  p95={ws['distribucion']['p95']:.2f}\")",
         "    for e in ws['scenarios']:",
         "        print(f\"  {e['name']:22} {e['dqs']:6.2f}  ({e['delta_vs_config']:+.2f})\")"),
    code("for ds, res in assess.items():",
         "    ws = dict(res['detalle']['weight_sensitivity'])",
         "    ws['distribucion_valores'] = res['detalle'].get('weight_sensitivity_distribucion', [])",
         "    _show(F.plot_weight_sensitivity(ws, F.figures_dir(), ds))"),
    md("## 4.4 · Incertidumbre: cuánto se movería con otra muestra",
        "",
        "El DQS es una media de medias: sin este cálculo, `92.07` se lee como un número",
        "exacto cuando en realidad es un estimador puntual. Bootstrap con reemplazo,",
        "300 remuestreos, IC 95 %.",
        "",
        "Ojo con `uniqueness` e `integrity`: se **fijan** al valor observado. Remuestrear",
        "filas con reemplazo duplica las claves primarias y hundiría la unicidad por un",
        "artefacto del remuestreo, no por el dataset (ver 4.12)."),
    code("for ds, res in assess.items():",
         "    boot = res['detalle']['bootstrap']",
         "    print(f\"\\n=== {ds} ===\")",
         "    for k, v in boot.items():",
         "        if isinstance(v, dict) and 'punto' in v:",
         "            print(f\"  {k:14} {v['punto']:7.2f}  IC [{v['ic_inf']:6.2f}, {v['ic_sup']:6.2f}]\"",
         "                  f\"  amplitud {v['amplitud']:.2f}  centrado={v['centrado']}\")",
         "    print(f\"  dimensiones fijadas: {boot['fix_dimensions']}\")"),
    code("for ds, res in assess.items():",
         "    _show(F.plot_bootstrap_ci(res['detalle']['bootstrap'], F.figures_dir(), ds))"),
    md("## 4.5 · Circularidad: el límite más serio",
        "",
        "La validación de este proyecto se hace contra `config/quality/catalogs/*.yaml`, y",
        "esos catálogos se derivaron de los valores **observados en el propio dataset**.",
        "",
        "Validar contra un catálogo hecho con esos mismos datos y obtener 100 % no",
        "demuestra que los datos sean correctos: demuestra que son consistentes consigo",
        "mismos. Un valor mal escrito en la fuente entra en el catálogo y se aprueba a sí",
        "mismo. Por eso este eje se declara en vez de esconderlo, y por eso el veredicto",
        "es `baja` y no `alta`.",
        "",
        "**No es un defecto del código: es un límite de la información disponible.**",
        "Solo se cerraría contrastando con una fuente externa (catálogo oficial de INEI,",
        "maestro UBIGEO), que no está en este workspace."),
    code("for ds, res in assess.items():",
         "    circ = res['detalle']['catalog_circularity']",
         "    print(f\"\\n=== {ds}: {circ['catalogos_circulares']}/{circ['catalogos_analizados']}\"",
         "          f\" catálogos circulares (umbral {circ['threshold_pct']}%) ===\")",
         "    for d in circ['detalle']:",
         "        print(f\"  {d['catalogo']:14} {d['pct_valores_derivados_del_dato']:6.2f}% derivado del dato\")",
         "        if d['valores_fuera_de_catalogo']:",
         "            print(f\"    fuera de catálogo: {d['valores_fuera_de_catalogo']}\")"),
    md("## 4.6 · Cobertura del universo: la incógnita más grande",
        "",
        "El dataset puede tener **cero nulos** en todas sus columnas obligatorias y aun",
        "así estar incompleto: eso mide nulos, no si la fuente publicó todos los",
        "siniestros.",
        "",
        "Sin el total oficial de ONSV/MTC, cualquier afirmación sobre «la siniestralidad",
        "vial en el Perú» basada en este dataset es una afirmación sobre **el dataset**, no",
        "sobre el país. Es el límite más relevante para quien use estos números."),
    code("for ds, res in assess.items():",
         "    cov = res['detalle']['coverage']",
         "    if not cov.get('disponible'):",
         "        print(f\"{ds}: sin columna de fecha configurada\")",
         "        continue",
         "    anios = cov['anios']",
         "    modal = max(anios, key=anios.get)",
         "    print(f\"\\n=== {ds} (columna '{cov['columna']}') ===\")",
         "    print(f\"  rango        : {cov['fecha_min']} -> {cov['fecha_max']}\")",
         "    print(f\"  registros por año: {anios}\")",
         "    print(f\"  años vacíos  : {cov['anios_vacios'] or 'ninguno'}\")",
         "    print(f\"  año modal    : {modal} con {cov['frac_anio_modal_pct']:.2f}% de los registros\")",
         "    print(f\"  fechas parseadas: {cov['n_fechas_parseadas']}  nulas: {cov['n_fechas_nulas']}\")",
         "    print(f\"  días únicos  : {cov['dias_unicos']}\")"),
    md("## 4.7 · Consistencia cruzada: ONSV contra cinemómetros",
        "",
        "Dos fuentes independientes con dos geografías distintas. Sin un maestro UBIGEO",
        "no hay forma de arbitrar cuál tiene razón, así que el pipeline **declara** la",
        "divergencia en vez de corregirla a ciegas: inventar una equivalencia entre",
        "departamentos y regiones sería un dato falso con apariencia de limpieza."),
    code("for ds, res in assess.items():",
         "    cross = res['detalle']['cross_dataset']",
         "    if not cross.get('enabled'):",
         "        print('consistencia cruzada desactivada')",
         "        continue",
         "    print(f\"\\n=== {ds} ===\")",
         "    for c in cross['comparaciones']:",
         "        if not c.get('disponible'):",
         "            print(f\"  {c.get('a')} vs {c.get('b')}: {c.get('motivo', 'no comparable')}\")",
         "            continue",
         "        col_a = f\"{c['a']}.{c['columnas'][0]}\"",
         "        col_b = f\"{c['b']}.{c['columnas'][1]}\"",
         "        print(f\"  {col_a} ({c['valores_a']} valores) vs {col_b} ({c['valores_b']} valores)\")",
         "        print(f\"    coincidentes   : {c['valores_comunes']}  (Jaccard {c['jaccard']})\")",
         "        print(f\"    solo en {c['a']}: {c['solo_en_a']}\")",
         "        print(f\"    solo en {c['b']}: {c['solo_en_b']}\")",
         "    print(f\"  veredicto: {cross['verdict']}\")",
         "    print(f\"  nota     : {cross['nota']}\")"),
    md("## 4.8 · Una dimensión vacía y las estimaciones",
        "",
        "Dos hallazgos que el número agregado esconde:",
        "",
        "- `integrity` vale **100 siempre**, porque no hay claves foráneas configuradas",
        "  entre datasets. No es buena señal: es una dimensión que no mide nada, y por eso",
        "  tiene su propia afirmación con veredicto `no_verificable`.",
        "- Las columnas **imputadas** convierten esas métricas en *estimaciones*, no en",
        "  mediciones. Deben declararse siempre que se usen."),
    code("for ds, res in assess.items():",
         "    integ = res['detalle']['integrity']",
         "    imput = res['detalle']['imputation']",
         "    print(f\"\\n=== {ds} ===\")",
         "    print(f\"  integridad = {integ['valor']}  ->  {integ['verdict']}\")",
         "    print(f\"    {integ['motivo']}\")",
         "    if imput.get('enabled') and imput.get('columnas_imputadas'):",
         "        print(f\"  imputadas: {imput['columnas_imputadas']}\")",
         "        print(f\"    {imput['motivo']}\")",
         "    else:",
         "        print('  sin imputaciones registradas en la config')"),
    md("## 4.9 · Deriva por huella de medición, no por commit",
        "",
        "Dos corridas solo son comparables si se hicieron con el **mismo método de",
        "medición**. La opción obvia sería agrupar por `git_commit`, pero tras integrar el",
        "ETL en el repositorio SIPAT el commit del padre cambia por motivos ajenos",
        "(editar un README) y produciría falsos positivos de deriva.",
        "",
        "Por eso existe `versioning.measurement_fingerprint()`: un hash de los ficheros que",
        "**producen** las métricas. `auditoria.py` queda deliberadamente fuera de esa",
        "huella: el auditor no produce la medición, y si estuviera dentro, tocar el auditor",
        "invalidaría justo la comparabilidad que la huella debe proteger."),
    code("for ds, res in assess.items():",
         "    drift = res['detalle']['drift']",
         "    d = drift['datasets'].get(ds, {})",
         "    print(f\"\\n=== {ds} ===\")",
         "    print(f\"  corridas totales           : {drift['n_runs_totales']}\")",
         "    print(f\"  huellas distintas          : {d.get('n_huellas')}\")",
         "    print(f\"  huella vigente             : {d.get('huella_vigente')}\")",
         "    print(f\"  ¿es la del código actual?  : {d.get('huella_es_actual')}\")",
         "    print(f\"  corridas de esa huella     : {d.get('n_runs_huella_vigente')}\")",
         "    dqs_h = f\"{d.get('dqs_min_huella_vigente')}/{d.get('dqs_max_huella_vigente')}\"",
         "    print(f\"  DQS dentro de la huella    : {dqs_h} -> rango {d.get('rango_huella_vigente')} puntos\")",
         "    print(f\"  DQS en TODAS las huellas   : {d.get('dqs_min')}/{d.get('dqs_max')}\")",
         "    print('    ^ esa diferencia entre huellas es un cambio de MÉTODO (correcciones),')",
         "    print('      no deriva: por eso el veredicto de reproducibilidad solo mira la huella vigente.')"),
    code("for ds, res in assess.items():",
         "    serie = res['detalle']['drift'].get('serie', [])",
         "    if serie:",
         "        _show(F.plot_dqs_evolution(serie, F.figures_dir(), ds))"),
    md("## 4.10 · El DQS que se está auditando",
        "",
        "Contexto de fondo: el número 92.07 es una media ponderada de estas dimensiones,",
        "y la frescura es baja **porque la fuente es histórica**, no por un defecto del",
        "proceso. Un dato de 2021 no es «fresco» en 2026, y eso es lo correcto."),
    code("_show(F.plot_dqs_dimensions({ds: res['dqs'] for ds, res in assess.items()},",
         "                           F.figures_dir()))"),
    md("## 4.11 · Los veredictos, de un vistazo",
        "",
        "Una fila por afirmación. El gris (`no_verificable`) no es un fallo del sistema: es",
        "el punto donde los datos disponibles dejan de poder responder la pregunta."),
    code("for ds, res in assess.items():",
         "    _show(F.plot_auditoria_claims(res['claims'], F.figures_dir(), ds))"),
    code("_matriz = pd.DataFrame({ds: {c['axis']: c['verdict'] for c in res['claims']}",
         "                     for ds, res in assess.items()})",
         "display(_matriz)",
         "print('\\nConteos por veredicto (NO es un índice de confiabilidad):')",
         "display(pd.DataFrame({ds: res['resumen_veredictos']",
         "                      for ds, res in assess.items()}).fillna(0).astype(int))"),
    md("## 4.12 · Errores a no heredar",
        "",
        "Defectos reales encontrados al implementar este apartado, cada uno con su",
        "test de regresión en `tests/unit/test_regressions.py`. El primero es el más",
        "interesante desde el punto de vista estadístico.",
        "",
        "### 1. El bootstrap sesgado por duplicar las claves primarias",
        "",
        "Remuestrear filas **con reemplazo** duplica las claves primarias, así que la",
        "dimensión *unicidad* se desploma por un artefacto del remuestreo. El primer",
        "resultado fue **punto 92.07 contra IC [86.45, 86.65]**: un intervalo que no",
        "contiene a su propio estimador puntual, que es la señal clásica de un bootstrap",
        "sesgado. Publicar esa «incertidumbre» habría sido un error metodológico.",
        "",
        "Arreglo: `bootstrap.fix_dimensions: [uniqueness, integrity]` en la config — las",
        "dimensiones invariantes al muestreo se fijan al valor observado.",
        "",
        "### 2. Elegir la huella de medición equivocada",
        "",
        "La «huella vigente» se elegía como la **más frecuente**, que en ese momento eran",
        "corridas antiguas con la medición ya corregida. El veredicto de reproducibilidad",
        "salía `baja` por un motivo inexistente. Ahora se elige la huella del código",
        "actual.",
        "",
        "### 3. El auditor dentro de la huella que lo audita",
        "",
        "Un glob `src/quality/*.py` incluía `auditoria.py` en la huella. Consecuencia:",
        "tocar el auditor invalidaba la comparabilidad de las corridas, que es",
        "exactamente lo que la huella debe evitar.",
        "",
        "### 4. `Agg` en el notebook",
        "",
        "`matplotlib.use('Agg')` está bien en un script, pero en un notebook **anula el",
        "render inline**: las celdas se ejecutan «sin error» y no muestran ninguna figura.",
        "Es el motivo de que este notebook incruste los PNG en base64 en vez de llamar a",
        "`plt.show()`.",
        "",
        "### 5. Figuras sobrescritas entre datasets",
        "",
        "Las figuras comunes usaban el mismo nombre para ONSV y para cinemómetros, así",
        "que una pisaba a la otra. Ahora cada nombre lleva su dataset.",
        "",
        "### 6. Evidencia de reproducibilidad que se contradecía a sí misma",
        "",
        "El `min`/`max` de DQS que accompanyaba a la afirmación de reproducibilidad se",
        "calculaba sobre **todas** las huellas de medición, al lado del rango de la",
        "vigente. La fila publicado decía `dqs_min=89.25, dqs_max=95.11,",
        "rango=0.00` con veredicto `alta`: se leía como una inestabilidad de casi seis",
        "puntos en un pipeline que es perfectamente determinista.",
        "",
        "Arreglo: `run_drift` expone ahora `dqs_min_huella_vigente` /",
        "`dqs_max_huella_vigente`, y la afirmación A1 usa esos. Los extremos globales",
        "siguen disponibles, con nombre explícito, para poder revisar los cambios de",
        "método."),
    md("## 4.13 · Conclusiones",
        "",
        "Lo que **sí** se puede sostener:",
        "",
        "1. El pipeline es **determinista**: misma huella de medición, mismo DQS. No es",
        "   determinismo declarado, es medido.",
        "2. Cada número es **trazable** hasta el fichero original, con checksum de fuente",
        "   y Bronze inmutable.",
        "3. El DQS es un **estimador muy preciso**: el IC es de décimas de punto.",
        "4. La limpieza **funciona y se ve** en la figura de nulos antes/después.",
        "",
        "Lo que **no** se puede sostener:",
        "",
        "1. La validación por catálogos es **circular**: es consistencia interna, no",
        "   validación externa.",
        "2. El DQS depende de los **pesos** que elegí: va del 70 al 100 según el escenario.",
        "3. La **cobertura del universo** es la incógnita más grande y sigue sin verificar.",
        "",
        "### Cómo decirlo en una sustentación",
        "",
        "> No: «nuestro pipeline tiene 92 % de confiabilidad». Ese número no existe.",
        "",
        "> Sí: «El DQS de nuestro dataset es 92.07 con un intervalo de confianza de",
        "> décimas de punto: es un estimador estable, determinista y trazable. Somos",
        "> conscientes de tres límites: la validación de catálogos es circular porque los",
        "> derivamos del propio dato, el score depende de los pesos que elegimos, y no",
        "> podemos verificar la cobertura del universo sin el total oficial de la ONSV».",
        "",
        "### Reproducibilidad",
        "",
        "Todo lo de este notebook se regenera con:",
        "",
        "```bash",
        "python scripts/run_pipeline.py      # Silver real",
        "python scripts/graficos_etl.py      # recalcula la tabla y dibuja",
        "```",
        "",
        "Los umbrales están en `config/quality/auditoria_rules.yaml`; el motor es",
        "`src/quality/auditoria.py`; el informe autocontenido se genera en",
        "`reports/auditoria/<dataset>_auditoria_*.html`."),
]

validate(rel, "04_auditoria_medicion")

SPEC = (
    (onsv, "01_exploracion_onsv.ipynb"),
    (cine, "02_exploracion_cinemometros.ipynb"),
    (silver, "03_silver_dqs_gate.ipynb"),
    (rel, "04_auditoria_medicion.ipynb"),
)


def build_all(out_dir=None) -> list:
    """Escribe los cuatro notebooks. Devuelve la lista de rutas escritas.

    Se separó del cuerpo del script para que los tests puedan construir los
    notebooks en un directorio temporal y compararlos con los versionados, sin
    tocar `notebooks/`.
    """
    out = Path(out_dir) if out_dir is not None else OUT
    out.mkdir(parents=True, exist_ok=True)
    escritos = []
    for celdas, nombre in SPEC:
        p = out / nombre
        p.write_text(
            json.dumps(notebook(celdas), ensure_ascii=False, indent=1), encoding="utf-8"
        )
        escritos.append(p)
    return escritos


def execute(paths, timeout: int = 1800) -> list:
    """Ejecuta los notebooks y guarda sus salidas (base64) en el propio .ipynb.

    `jupyter nbconvert --execute` no está instalado en este entorno; `nbclient`
    sí, y hace lo mismo. Los notebooks se versionan SIN salidas para no meter
    pesos ni resultados rancios en Git; esta función es para querer mirar el
    análisis renderizado sin ejecutar nada a mano.
    """
    import nbformat
    from nbclient import NotebookClient

    hechos = []
    for p in paths:
        nb = nbformat.read(p, as_version=4)
        client = NotebookClient(
            nb,
            timeout=timeout,
            kernel_name="python3",
            # El kernel arranca en notebooks/: es donde están los .csv del ETL.
            resources={"metadata": {"path": str(p.parent.resolve())}},
        )
        client.execute()
        nbformat.write(nb, p)
        n_img = sum(
            1
            for c in nb.cells
            for o in getattr(c, "outputs", [])
            if "image/png" in o.get("data", {})
        )
        client.log.info("ejecutado %s (%d figuras embebidas)", p.name, n_img)
        print(f"  [ok] {p.name}: {len(nb.cells)} celdas, {n_img} figuras embebidas")
        hechos.append(p)
    return hechos


if __name__ == "__main__":
    import argparse

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--execute", action="store_true",
        help="ejecuta los notebooks y guarda las salidas (requiere nbclient, ~6 min)",
    )
    ap.add_argument("--only", default="", help="genera/ejecuta solo este notebook")
    args = ap.parse_args()

    escritos = build_all()
    print("notebooks generados:", [p.name for p in escritos])
    objetivo = [p for p in escritos if args.only in p.name] if args.only else escritos
    if args.execute:
        print("ejecutando (puede tardar varios minutos)...")
        execute(objetivo)
