# -*- coding: utf-8 -*-
"""Genera los notebooks de exploracion de datos reales (notebooks/01, 02).

Se construyen desde Python para garantizar JSON valido y evitar el escapado
manual de cadenas en un .ipynb. Ejecutar:  python scripts/build_notebooks.py
"""
from __future__ import annotations

import json
from itertools import count
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "notebooks"
OUT.mkdir(parents=True, exist_ok=True)

_CELL_IDS = count(1)


def _cell_id() -> str:
    """nbformat >= 4.5 exige 'id' en cada celda."""
    return f"cell-{next(_CELL_IDS):03d}"


def md(*lines: str) -> dict:
    return {
        "cell_type": "markdown",
        "id": _cell_id(),
        "metadata": {},
        "source": [l + "\n" for l in lines][:-1] + [lines[-1]],
    }


def code(*lines: str) -> dict:
    src = [l + "\n" for l in lines][:-1] + [lines[-1]]
    return {
        "cell_type": "code",
        "id": _cell_id(),
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": src,
    }


def notebook(cells: list) -> dict:
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def validate(cells: list, name: str) -> None:
    """Compila cada celda de codigo: un error de sintaxis aqui solo apareceria
    al abrir el notebook, que es exactamente cuando mas molesta."""
    for i, c in enumerate(cells):
        if c["cell_type"] != "code":
            continue
        src = "".join(c["source"]) if isinstance(c["source"], list) else c["source"]
        try:
            compile(src, f"{name}::cell{i}", "exec")
        except SyntaxError as exc:
            raise SystemExit(
                f"{name}: celda de codigo {i} con error de sintaxis: {exc.msg} (linea {exc.lineno})\n"
                f"  {exc.text!r}"
            ) from exc


PRELUDE = [
    "import sys",
    "from pathlib import Path",
    "",
    "import numpy as np",
    "import pandas as pd",
    "",
    "ROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()",
    "sys.path.insert(0, str(ROOT / 'src'))",
    "sys.path.insert(0, str(ROOT))",
    "",
    "from src.utils.configloader import expand_path, load_catalogs, load_settings, load_sources",
    "",
    "pd.set_option('display.max_columns', 40)",
    "pd.set_option('display.width', 160)",
    "",
    "SETTINGS = load_settings()",
]

# ---------------------------------------------------------------- ONSV ----

onsv = [
    md(
        "# 01 · Perfilado del crudo ONSV",
        "",
        "Fase CRISP-DM **Data Understanding**. Carga el XLSX real *tal como llega* y",
        "documenta los problemas que la capa de limpieza debe resolver.",
        "",
        "El objetivo NO es limpiar: es ver el dato sucio antes de decidir qué se limpia.",
        "",
        "Preguntas que responde:",
        "",
        "1. Donde esta la cabecera real del fichero?",
        "2. Que columnas mezclan tipos y por qué no son escribibles en Parquet?",
        "3. Que tanta informacion se pierde en cada limpieza?",
        "4. Que reglas de dominio se pueden escribir a partir de la observacion?",
    ),
    code(*PRELUDE, 'spec = load_sources()["onsv"].copy()', 'spec["path"] = expand_path(spec["path"])',
         'print("Fuente:", spec["path"])', 'print("Existe:", Path(spec["path"]).exists())'),
    md("## 1.1 · Donde esta la cabecera",
        "",
        "El XLSX de ONSV tiene un preambulo institucional antes de los encabezados.",
        "Leerlo con `pd.read_excel(path)` sin indicar `header` toma la primera fila",
        "del preambulo como cabecera y todos los nombres quedan corruptos."),
    code('naive = pd.read_excel(spec["path"], header=0, nrows=3)',
         'correct = pd.read_excel(spec["path"], header=spec["header_row"], nrows=3)',
         "",
         'print("Con header=0 (ingenuo), primeras columnas:")',
         "print(list(naive.columns)[:6], \"...\")",
         "",
         'print(f"Con header_row={spec[\'header_row\']} (configurado):")',
         "print(list(correct.columns))"),
    md("## 1.2 · Nombres problematicos",
        "",
        "Acentos, signos de interrogacion de apertura y espacios dobles. Cada uno",
        "requiere una decision explicita de renombrado, no un `.strip()` generico."),
    code("cols = list(correct.columns)",
         "problemas = {",
         "    'espacios dobles': [c for c in cols if '  ' in c],",
         "    'signo apertura (¿)': [c for c in cols if '¿' in c],",
         "    'acentos': [c for c in cols if any(ch in c for ch in 'ÁÉÍÓÚÑáéíóúñ')],",
         "}",
         "for k, v in problemas.items():",
         "    print(f'{k}: {len(v)}')",
         "    for c in v:",
         "        print('    ', repr(c))"),
    md("## 1.3 · Tipos mezclados (el problema que rompia Bronze)",
        "",
        "Parquet exige **un tipo por columna**. Las columnas `object` que mezclan",
        "tipos no son escribibles: PyArrow lanza",
        "`Expected bytes, got a 'datetime.datetime' object`."),
    code("import datetime as dt", "",
         'raw = pd.read_excel(spec["path"], header=spec["header_row"])',
         'print(f"Crudo: {raw.shape[0]:,} filas x {raw.shape[1]} columnas\\n")',
         "",
         "for col in raw.columns:",
         "    s = raw[col]",
         "    if s.dtype != object:",
         "        continue",
         "    tipos = set(type(v).__name__ for v in s.dropna())",
         "    if len(tipos) > 1:",
         "        print(f'{col!r} -> {sorted(tipos)}')",
         "        for v in s.dropna().unique()[:3]:",
         "            print('     ', repr(v))"),
    md("### Comprobacion directa: se puede escribir en Parquet?"),
    code("import tempfile", "",
         'tmp = Path(tempfile.gettempdir()) / "nb_bronze_test.parquet"',
         "try:",
         '    raw.to_parquet(tmp, engine="pyarrow", index=False)',
         '    print("OK: el crudo se escribe directo en Parquet")',
         "except Exception as exc:",
         '    print("FALLA (como en produccion):", type(exc).__name__)',
         "    print('  ', str(exc)[:140])"),
    md("## 1.4 · La solucion aplicada: `_parquet_safe()`",
        "",
        "Normaliza **por contenido**, no por nombre de columna, en tres pasos:",
        "numerico -> fecha -> literal, aceptando la conversion solo si no destruye valores."),
    code("from src.extract.register_raw import _parquet_safe", "",
         "fixed = _parquet_safe(raw.copy())",
         'print(f"Tras _parquet_safe: {fixed.shape[0]:,} filas x {fixed.shape[1]} columnas")',
         "fixed.to_parquet(tmp, engine='pyarrow', index=False)",
         'print("Se escribe en Parquet: si\\n")',
         "",
         "back = pd.read_parquet(tmp)",
         "assert len(back) == len(raw), 'no se pierden filas'",
         'print("Filas preservadas:", f"{len(back):,}")',
         "",
         "cambiadas = [c for c in raw.columns if str(raw[c].dtype) != str(back[c].dtype)]",
         "print('Columnas cuyo tipo cambio en Bronze:', cambiadas)"),
    md("## 1.5 · Completitud y nulos por columna",
        "",
        "Base para decidir imputaciones. Solo se imputa lo que tiene sentido imputar."),
    code("nulos = pd.DataFrame({",
         "    'nulos': raw.isna().sum(),",
         "    'pct_nulos': (raw.isna().mean() * 100).round(2),",
         "    'n_unicos': raw.nunique(dropna=True),",
         "    'dtype': raw.dtypes.astype(str),",
         "}).sort_values('pct_nulos', ascending=False)",
         "nulos[nulos['pct_nulos'] > 0]"),
    md("## 1.6 · Categoricas: que valores existen",
        "",
        "Base empirica de `config/quality/catalogs/onsv.yaml`."),
    code('for col in ["CLASE SINIESTRO", "CONDICIÓN CLIMÁTICA", "ZONA", "RED VIAL"]:',
         "    if col not in raw.columns:",
         "        continue",
         '    print(f"\\n=== {col} ({raw[col].nunique()} unicos) ===")',
         "    print(raw[col].value_counts(dropna=False).head(12).to_string())"),
    md("## 1.7 · El problema de los acentos",
        "",
        "`CAÍDA DE PASAJERO` -> `CAIDA DE PASAJERO` tras `fold_accents`.",
        "Si el catalogo mantiene el acento, la comparacion falla siempre."),
    code('cats = load_catalogs("onsv")',
         'print("Catalogo (forma plegada, la que produce Silver):")',
         "for v in cats['clase']:",
         "    print('   ', v)",
         "",
         'print("\\nValores en el crudo:")',
         "cat_upper = {c.upper() for c in cats['clase']}",
         'for v in sorted(raw["CLASE SINIESTRO"].dropna().unique()):',
         "    marca = 'OK' if v.upper() in cat_upper else 'DIFIERE'",
         "    print(f'    {v!r}  {marca}')"),
    md("## 1.8 · Coordenadas: el Peru es negativo",
        "",
        "Este detalle hizo fallar la dimension de validez en una version anterior:",
        "un umbral `>= 0` aplicado a coordenadas de un pais del hemisferio sur."),
    code('lat = pd.to_numeric(raw["COORDENADAS LATITUD"].astype(str)',
         '                       .str.replace("°", "", regex=False), errors="coerce")',
         'lon = pd.to_numeric(raw["COORDENADAS  LONGITUD"].astype(str)',
         '                       .str.replace("°", "", regex=False), errors="coerce")',
         "",
         'print("Latitud :", round(lat.min(), 4), "a", round(lat.max(), 4))',
         'print("Longitud:", round(lon.min(), 4), "a", round(lon.max(), 4))',
         'print(f"\\nPct latitudes  negativas: {(lat < 0).mean() * 100:.1f}%")',
         'print(f"Pct longitudes negativas: {(lon < 0).mean() * 100:.1f}%")',
         'print("\\n=> Un chequeo de validez >= 0 puntuaria 0% a ambas columnas.\\n")',
         "dentro = lat.between(-18.5, 0.2) & lon.between(-81.5, -68.5)",
         'print(f"Dentro del territorio peruano: {dentro.mean() * 100:.1f}%")'),
    md("## 1.9 · Fechas: DD/MM vs MM/DD",
        "",
        "Pandas interpreta `01/05/2021` como 1 de mayo cuando el dato es 5 de enero."),
    code('fechas_texto = raw["FECHA SINIESTRO"].dropna().astype(str)',
         "print('Muestra:', fechas_texto.head(5).tolist(), '\\n')",
         'ingenua = pd.to_datetime(fechas_texto, errors="coerce")',
         'correcta = pd.to_datetime(fechas_texto, format="%d/%m/%Y", errors="coerce")',
         "",
         'print(f"NaT con parsing por defecto: {ingenua.isna().sum()}")',
         'print(f"NaT con format=%d/%m/%Y : {correcta.isna().sum()}")',
         'print(f"\\nRango correcto: {correcta.min().date()} a {correcta.max().date()}")',
         "print('Rango ingenuo :', ingenua.min(), 'a', ingenua.max())",
         'print("\\n=> Configurar date_columns en settings.yaml NO es opcional.")'),
    md("## 1.10 · Duplicados en la clave primaria"),
    code('clave = "CÓDIGO SINIESTRO"',
         'print("Filas        :", f"{len(raw):,}")',
         'print("Codigos unicos:", f"{raw[clave].nunique():,}")',
         'print("Duplicados   :", int(raw[clave].duplicated().sum()))',
         'print("Nulos en la PK:", int(raw[clave].isna().sum()))',
         "",
         "dup = raw[raw[clave].duplicated(keep=False)].sort_values(clave)",
         "if len(dup):",
         "    print('\\nFilas implicadas:', len(dup))",
         "    print(dup[[clave, 'FECHA SINIESTRO', 'CLASE SINIESTRO']].head(10).to_string(index=False))",
         "else:",
         "    print('\\nNo hay duplicados: la PK codigo es unica de origen.')"),
    md("## 1.11 · Perfil del target",
        "",
        "`fallecidos` es el target de `model_ready`. Su distribucion determina que modelo",
        "tendra sentido (conteo desbalanceado -> Poisson/Tweedie, no regresion lineal)."),
    code('f = pd.to_numeric(raw["CANTIDAD DE FALLECIDOS"], errors="coerce").fillna(0)',
         "print(f.describe().to_string())",
         'print("\\nDistribucion de fallecidos por siniestro:")',
         "print(f.astype(int).value_counts().sort_index().head(10).to_string())"),
    md("## 1.12 · Variables categoricas frente al target"),
    code('f = pd.to_numeric(raw["CANTIDAD DE FALLECIDOS"], errors="coerce").fillna(0)',
         'for col in ["CLASE SINIESTRO", "ZONA", "CONDICIÓN CLIMÁTICA"]:',
         "    if col not in raw.columns:",
         "        continue",
         '    g = raw.assign(_f=f).groupby(col, dropna=False)["_f"].agg(["count", "mean"])',
         "    g['pct'] = (g['count'] / len(raw) * 100).round(2)",
         "    g['media_fallecidos'] = g['mean'].round(3)",
         '    print(f"\\n--- {col} ---")',
         "    print(g[['pct', 'media_fallecidos']].head(10).to_string())",
         'print(f"\\nMedia global: {f.mean():.3f} fallecidos por siniestro")'),
    md("## 1.13 · Conclusiones",
        "",
        "| Hallazgo | Decision de diseno |",
        "|---|---|",
        "| Preambulo de 4 filas | `header_row: 4` en la config de la fuente |",
        "| Nombres con acentos, `¿?` y espacios dobles | mapa `rename` canonico |",
        "| Fechas DD/MM ambiguas | `date_columns` con formatos explicitos |",
        "| Coordenadas con simbolo grado | `numeric_strip_chars` |",
        "| Columnas `object` con tipos mezclados | `_parquet_safe()` en Bronze |",
        "| Acentos en categorias | catalogos en forma plegada + comparacion `_norm()` |",
        "| Coordenadas negativas (Peru) | `validity` usa el rango del contrato |",
        "",
        "Todos estos puntos estan cubiertos por `tests/unit/test_regressions.py`."),
]

# -------------------------------------------------------- CINEMOMETROS ----

cine = [
    md(
        "# 02 · Perfilado del crudo Cinemometros (SUTRAN)",
        "",
        "Segunda fuente, deliberadamente distinta: 160.018 filas en CSV frente a un XLSX",
        "de 9.106 filas. Aqui los problemas son de **normalizacion**, no de formato:",
        "",
        "- `REGION` con `LIMA` y `Lima` a la vez (doble caja)",
        "- `CARRETERA` con `Panamericana Sur` frente a `PANAMERICANA SUR`",
        "- `lat`/`lon` que duplican exactamente `LATITUD`/`LONGITUD`",
        "- Fechas en formato numerico compactado (`20191031`)",
        "",
        "Al ser un dataset mucho mayor, se mide tambien el coste de la normalizacion.",
    ),
    code(*PRELUDE, 'spec = load_sources()["cinemometros"].copy()', 'spec["path"] = expand_path(spec["path"])',
         'print("Fuente:", spec["path"])', 'print("Existe:", Path(spec["path"]).exists())'),
    code("import csv", "",
         "with open(spec['path'], encoding='utf-8-sig') as fh:",
         "    reader = csv.reader(fh)",
         "    header = next(reader)",
         "    first = next(reader)",
         'print("Columnas:", len(header))',
         "for h in header:",
         "    print('   ', repr(h))",
         "print('\\nPrimera fila:'); print(first)"),
    md("## 2.1 · La doble caja en REGION",
        "",
        "El problema de normalizacion clasico: la misma entidad escrita de dos formas."),
    code('cine = pd.read_csv(spec["path"], encoding="utf-8-sig", low_memory=False)',
         'print(f"Crudo: {cine.shape[0]:,} filas x {cine.shape[1]} columnas\\n")',
         'print("Valores de REGION tal cual llegan:")',
         "print(cine['REGION'].value_counts(dropna=False).to_string())"),
    md("### Cuantas filas se ven afectadas por la doble caja"),
    code('es_minuscula = cine["REGION"].astype(str) != cine["REGION"].astype(str).str.upper()',
         'print("Filas con REGION no normalizada:", f"{int(es_minuscula.sum()):,}",',
         '      f"({es_minuscula.mean()*100:.2f}%)")',
         "print('Valores afectados:', sorted(cine.loc[es_minuscula, 'REGION'].unique()))",
         'print("\\n=> Sin case_normalize, el mismo departamento seria dos categorias distintas.")'),
    md("## 2.2 · CARRETERA tambien tiene doble caja"),
    code('print("Valores de CARRETERA:")',
         "print(cine['CARRETERA'].value_counts(dropna=False).head(20).to_string())"),
    md("## 2.3 · Fechas en formato numerico compactado",
        "",
        "`20191031` es un entero, no una fecha. Sin `date_columns` con `%Y%m%d` el pipeline",
        "no puede parsearlas y la regla critica `fecha_parsable` falla."),
    code('print("Dtype crudo de FECHA_PAPELETA:", cine["FECHA_PAPELETA"].dtype)',
         "print('Muestra:', cine['FECHA_PAPELETA'].head(5).tolist(), '\\n')",
         'parseada = pd.to_datetime(cine["FECHA_PAPELETA"], format="%Y%m%d", errors="coerce")',
         'print("NaT con format=%Y%m%d:", int(parseada.isna().sum()))',
         'print("Rango:", parseada.min(), "a", parseada.max())',
         'print("\\n=> Configurar el formato compacto es obligatorio, no opcional.")'),
    md("## 2.4 · Columnas redundantes: lat/lon vs LATITUD/LONGITUD",
        "",
        "La configuracion descarta `lat`/`lon`. Este notebook verifica que la duplicacion es",
        "exacta antes de tomar esa decision."),
    code('if "lat" in cine.columns and "lon" in cine.columns:',
         "    mismo_lat = (cine['lat'].astype(float) == cine['LATITUD'].astype(float)).mean()",
         "    mismo_lon = (cine['lon'].astype(float) == cine['LONGITUD'].astype(float)).mean()",
         '    print(f"Pct de filas donde lat == LATITUD: {mismo_lat*100:.2f}%")',
         '    print(f"Pct de filas donde lon == LONGITUD: {mismo_lon*100:.2f}%")',
         '    print("\\n=> Duplicacion exacta: se descartan en clean (drop_columns).")',
         "else:",
         '    print("El fichero ya no trae lat/lon.")'),
    md("## 2.5 · Nulos y completitud"),
    code("nulos = pd.DataFrame({",
         "    'nulos': cine.isna().sum(),",
         "    'pct_nulos': (cine.isna().mean() * 100).round(2),",
         "    'n_unicos': cine.nunique(dropna=True),",
         "}).sort_values('pct_nulos', ascending=False)",
         "nulos[nulos['pct_nulos'] > 0]"),
    md("## 2.6 · Velocidades: el dominio de negocio",
        "",
        "El exceso de velocidad es la magnitud accionable. Se derivan `exceso_kmh` y",
        "`excede_limite` en `src/transform/features.py`."),
    code('v = pd.to_numeric(cine["VELOCIDAD_DETECTADA"], errors="coerce")',
         'lim = pd.to_numeric(cine["LIMITE_VELOCIDAD"], errors="coerce")',
         "v, lim = v.dropna(), lim.loc[v.dropna().index]",
         'print("Velocidad detectada:")',
         "print(v.describe().round(2).to_string(), '\\n')",
         'print("Limite de velocidad:")',
         "print(lim.value_counts(dropna=False).head(10).to_string(), '\\n')",
         "exceso = (v - lim).clip(lower=0)",
         'print("Exceso sobre el limite (km/h):")',
         "print(exceso.describe().round(2).to_string())",
         'print(f"\\nPct que excede el limite: {(exceso > 0).mean()*100:.2f}%")',
         'print("Pct que excede mas de 20 km/h: %.2f%%" % ((exceso > 20).mean()*100))'),
    md("### Outliers: se reportan, no se eliminan",
        "",
        "`outlier_policy: report`. Un exceso alto es informacion real, no basura."),
    code("q1, q3 = exceso.quantile([0.25, 0.75])",
         "iqr = q3 - q1",
         "lim_sup = q3 + 1.5 * iqr",
         'print(f"IQR: Q1={q1:.1f}, Q3={q3:.1f}, umbral superior={lim_sup:.1f} km/h")',
         'print(f"Outliers por IQR: {int((exceso > lim_sup).sum()):,} '
         '({(exceso > lim_sup).mean()*100:.2f}%)")',
         'print("\\n=> Se reportan en el perfil. Borrarlos seria una decision analitica, no de limpieza.")'),
    md("## 2.7 · Duplicados en la clave primaria"),
    code('clave = "NRO_DETECCION"',
         'print("Filas         :", f"{len(cine):,}")',
         'print("Detecciones   :", f"{cine[clave].nunique():,}")',
         'print("Duplicados    :", int(cine[clave].duplicated().sum()))',
         'print("Nulos en la PK:", int(cine[clave].isna().sum()))',
         "if cine[clave].duplicated().any():",
         "    d = cine[cine[clave].duplicated(keep=False)]",
         '    print("\\nMuestra de duplicados:")',
         "    print(d.head(10).to_string())",
         "else:",
         '    print("\\nPK unica: no se requiere dedupe en este dataset.")'),
    md("## 2.8 · Distribucion geografica"),
    code("print('Top 10 regiones por numero de detecciones:')",
         "print(cine['REGION'].value_counts().head(10).to_string())"),
    md("## 2.9 · Conclusion: contraste con ONSV",
        "",
        "| Aspecto | ONSV (9.106 filas) | Cinemometros (160.018 filas) |",
        "|---|---|---|",
        "| Formato | XLSX con preambulo | CSV plano |",
        "| Problema dominante | estructura (nombres, tipos) | normalizacion (caja, acentos) |",
        "| Fechas | `DD/MM/YYYY` ambiguo | `%Y%m%d` numerico |",
        "| Columnas redundantes | ninguna | `lat`/`lon` duplican |",
        "| PK | `codigo`, unica | `nro_deteccion`, unica |",
        "| Nulos relevantes | `vehiculos_danados` 30.9% | ninguno critico |",
        "",
        "Un pipeline que solo funciona con uno de los dos formatos no es un pipeline."),
]

validate(onsv, "01_exploracion_onsv")
validate(cine, "02_exploracion_cinemometros")

silver = [
    md(
        "# 03 · Silver, DQS y quality gate",
        "",
        "Fase CRISP-DM **Data Preparation / Evaluation**. Este notebook carga la Silver",
        "ya generada por el pipeline y muestra:",
        "",
        "1. Que hizo la limpieza (TransformationLog, no conjeturas)",
        "2. Como se descompone el DQS en sus seis dimensiones",
        "3. Que pasaria si una regla critica fallara",
        "4. Las agregaciones Gold generadas con SQL sobre DuckDB",
        "",
        "Requisito previo: `python scripts/run_pipeline.py`",
    ),
    code(*PRELUDE, "from src.cleaning.transform_log import TransformationLog", "",
         "from pathlib import Path", "",
         'SILVER = ROOT / "data" / "silver"',
         'print("Silver disponible:", SILVER.exists())',
         'print([p.name for p in sorted(SILVER.glob("*.parquet"))] if SILVER.exists() else "ejecuta el pipeline")'),
    md("## 3.1 · Que se limpio realmente: el TransformationLog",
        "",
        "No se supone nada: cada operacion queda registrada con el numero de registros",
        "afectados y ejemplos antes/despues."),
    code("import json", "",
         "runs = sorted((ROOT / 'artifacts' / 'runs').glob('run-*'), reverse=True)",
         'print("Ultimo run:", runs[0].name if runs else "ninguno")',
         "tlog_path = runs[0] / 'transform_log_onsv.json' if runs else None",
         "if tlog_path and tlog_path.exists():",
         "    tlog = json.loads(tlog_path.read_text(encoding='utf-8'))",
         "    ops = tlog['operations']",
         "    print(f'\\n{len(ops)} operaciones registradas\\n')",
         "    resumen = pd.DataFrame([{",
         "        'operacion': o['operation'],",
         "        'columna': o.get('column'),",
         "        'afectados': o.get('n_affected'),",
         "        'estrategia': o.get('strategy'),",
         "    } for o in ops])",
         "    print(resumen.to_string(index=False))",
         "else:",
         "    print('No hay transform log: ejecuta el pipeline.')"),
    md("## 3.2 · Silver: estructura y contrato"),
    code("from src.utils.configloader import load_contract", "",
         "from src.validation.contract import validate_contract", "",
         'sl = pd.read_parquet(SILVER / "onsv_silver_1.0.parquet")',
         'print(f"Silver ONSV: {sl.shape[0]:,} filas x {sl.shape[1]} columnas\\n")',
         "print('Columnas canónicas:')",
         "for i, c in enumerate(sl.columns, 1):",
         "    print(f'  {i:2d}. {c:<28} {sl[c].dtype}')"),
    code('contract = load_contract("onsv", SETTINGS)',
         "res = validate_contract(sl, contract)",
         'print(f"\\nContrato valido: {res[\'valid\']}  (errores: {res[\'n_errors\']})")',
         "if res['errors']:",
         "    for col, rule, msg in res['errors'][:10]:",
         "        print(f'   {col}: {rule} -> {msg}')",
         'print("\\nColumnas extra toleradas (allow_extra):")',
         "print('  ', res['details_by_column'].get('__extra_columns'))"),
    md("## 3.3 · DQS descompuesto",
        "",
        "El DQS es una media ponderada de seis dimensiones. Verlas por separado explica",
        "mucho mas que el numero final."),
    code("from src.quality import dimensions", "",
         "from src.utils.configloader import load_catalogs", "",
         'cd = load_contract("onsv", SETTINGS)',
         'dqs = dimensions.compute_dqs(sl, SETTINGS, cd, load_catalogs("onsv"), dataset="onsv")',
         "pesos = dqs['weights']",
         "print('Dimension      Peso    Valor   Aporte')",
         "print('-' * 46)",
         "for k in pesos:",
         "    print(f'{k:<14} {pesos[k]:.2f}  {dqs[k]:7.2f}  {dqs[k]*pesos[k]:7.2f}')",
         "print('-' * 46)",
         "print(f'{\"DQS\":<14} {\"1.00\":<6} {\"\":>7}  {dqs[\"dqs\"]:7.2f}')",
         "print(f'\\nFilas evaluadas: {dqs[\"n_rows\"]:,}')",
         "print(f'Columna de frescura: {dqs[\"freshness_column\"]} (ventana {dqs[\"freshness_window_days\"]} d)')"),
    md("### Por que la frescura es baja y eso es correcto",
        "",
        "Los siniestros son de 2021-2025. Un registro de 2021 no es fresco en 2026: es un",
        "dato historico. Por eso la frescura pesa 0.08 y el sistema lo dice en vez de"),
    code("print(f'Frescura: {dqs[\"freshness\"]:.2f}')",
         "print('Es una consecuencia de que la fuente es historica, no un defecto del proceso.')",
         "print('Si la fuente se actualiza, el DQS sube solo, sin tocar configuracion.')"),
    md("## 3.4 · Validacion de la correccion del DQS",
        "",
        "Si `validity` aplicase `>= 0` a toda columna numerica, las coordenadas del Peru",
        "(negativas) puntuarian 0%. Comprobamos que ya no es asi."),
    code('rango_lat = (sl["latitud"].between(-18.5, 0.2)).mean() * 100',
         'rango_lon = (sl["longitud"].between(-81.5, -68.5)).mean() * 100',
         'print(f"Latitud dentro de rango:  {rango_lat:.2f}%")',
         'print(f"Longitud dentro de rango: {rango_lon:.2f}%")',
         'print(f"\\n=> Un umbral >= 0 habria dado 0.00% en ambas. Correccion aplicada.")'),
    md("## 3.5 · Features derivadas"),
    code("features = [c for c in sl.columns if c not in load_contract('onsv', SETTINGS)['contract']['columns']]",
         "print('Features derivadas por src/transform/features.py:')",
         "for f in features:",
         "    print(f'   {f:<22} {sl[f].dtype}')",
         "",
         "if 'tramo_dia' in sl.columns:",
         '    print("\\nSiniestros por tramo del dia:")',
         "    print(sl['tramo_dia'].value_counts().to_string())"),
    md("## 3.6 · Simular el fallo de una regla critica",
        "",
        "El sistema esta disenado para detenerse. Inyectamos una violacion y comprobamos",
        "que el gate la detecta y que el registro llega a cuarentena."),
    code("from src.quality.domain_rules import detect_violations", "",
         "from src.quality.gates import evaluate_gate", "",
         "from src.utils.configloader import load_quality_rules", "",
         "contaminado = sl.copy()",
         "contaminado.loc[contaminado.index[:5], 'latitud'] = 99.0",
         "print('Inyectadas 5 coordenadas fuera del rango peruano (99.0)\\n')",
         "viol = detect_violations(",
         "    contaminado,",
         "    load_quality_rules()['domain_rules']['onsv']['rules'],",
         "    load_catalogs('onsv'),",
         ")",
         "crit = [v for v in viol if v['severity'] == 'critical']",
         "print('Reglas criticas disparadas:')",
         "for v in crit:",
         "    print(f\"   {v['rule']}: {v['count']} registros\")",
         "",
         "gate = evaluate_gate(",
         "    dimensions.compute_dqs(contaminado, SETTINGS, cd, load_catalogs('onsv'), dataset='onsv'),",
         "    viol,",
         "    load_quality_rules(),",
         "    'onsv',",
         "    'demo-run',",
         ")",
         'print(f"\\nGate resultante: {gate[\'status\']}  (criticos: {gate[\'n_critical_errors\']})")',
         'print("\\n=> El gate bloquea la publicacion en Gold model_ready.")'),
    md("## 3.7 · Agregaciones Gold generadas con SQL",
        "",
        "Declaradas en `config/quality/catalogs/*.yaml` y ejecutadas sobre DuckDB."),
    code("from src.utils.configloader import load_aggregations", "",
         "print('Agregaciones declaradas para onsv:')",
         "for spec in load_aggregations('onsv'):",
         "    val = f\", value={spec['value']}\" if 'value' in spec else ''",
         "    print(f\"   {spec['name']:<32} kind={spec['kind']:<9} by={spec['by']}{val}\")"),
    code("agg = sorted((ROOT / 'reports' / 'quality' / 'aggregations').glob('onsv_*.json'))",
         "if agg:",
         "    latest = json.loads(agg[-1].read_text(encoding='utf-8'))",
         "    for name, rows in latest['aggregations'].items():",
         "        print(f'\\n--- {name} ({len(rows)} filas) ---')",
         "        print(pd.DataFrame(rows).head(8).to_string(index=False))",
         "else:",
         "    print('No hay agregaciones: ejecuta el pipeline.')"),
    md("## 3.8 · Consulta SQL directa sobre la capa Silver",
        "",
        "DuckDB lee los Parquet: no hay base de datos que mantener."),
    code("import duckdb", "",
         'silver_glob = str((ROOT / "artifacts" / "lineage" / "sipat_lineage.duckdb").resolve())',
         "con = duckdb.connect(silver_glob, read_only=True)",
         "try:",
         "    print(con.execute(",
         '        "SELECT dataset, layer, rows, cols FROM dataset_lines ORDER BY created_at DESC LIMIT 6"',
         "    ).df().to_string(index=False))",
         "finally:",
         "    con.close()"),
    code("con = duckdb.connect()",
         "try:",
         "    sl_path = str((ROOT / 'data' / 'silver' / 'onsv_silver_1.0.parquet').resolve())",
         "    out = con.execute(",
         '        "SELECT departamento, COUNT(*) AS n, SUM(fallecidos) AS muertos "',
         "        + f\"FROM read_parquet('{sl_path}') \"",
         '        + "GROUP BY 1 ORDER BY muertos DESC, n DESC LIMIT 10"',
         "    ).df()",
         "    print(out.to_string(index=False))",
         "finally:",
         "    con.close()"),
    md("## 3.9 · Conclusiones",
        "",
        "1. La limpieza deja traza auditable en el TransformationLog.",
        "2. El DQS se descompone y cada dimensión es explicable.",
        "3. El gate detiene la publicación ante una regla critica (ver 3.6).",
        "4. Las agregaciones son SQL en YAML, no codigo.",
        "5. La capa Silver es consultable con SQL sin servidor adicional."),
]

validate(silver, "03_silver_dqs_gate")

(OUT / "01_exploracion_onsv.ipynb").write_text(
    json.dumps(notebook(onsv), ensure_ascii=False, indent=1), encoding="utf-8"
)
(OUT / "02_exploracion_cinemometros.ipynb").write_text(
    json.dumps(notebook(cine), ensure_ascii=False, indent=1), encoding="utf-8"
)
(OUT / "03_silver_dqs_gate.ipynb").write_text(
    json.dumps(notebook(silver), ensure_ascii=False, indent=1), encoding="utf-8"
)
print("notebooks generados:", [p.name for p in sorted(OUT.glob("*.ipynb"))])
